
name: Users workflow

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
    test-users:
        name: "test users"
        runs-on: ubuntu-latest
        env:
          OPAMWITHTEST: true
          OPAMVERBOSE: true
        steps:
        - uses: actions/checkout@v4

        - uses: ocaml/setup-ocaml@v3
          with:
            ocaml-compiler: 4.14.x
            opam-local-packages:

        - run: opam install ./elpi.opam
          env:
            OPAMWITHTEST: false
            
        - run: opam pin --ignore-constraints-on elpi add coq-elpi https://github.com/fissored/coq-elpi.git#fix-modes
        - run: opam pin --ignore-constraints-on elpi add coq-hierarchy-builder https://github.com/fissored/hierarchy-builder.git#fix-mode
        - run: opam pin --ignore-constraints-on elpi add coq-mathcomp-ssreflect https://github.com/math-comp/math-comp.git#master
        - run: opam pin --ignore-constraints-on elpi add coq-mathcomp-fingroup https://github.com/math-comp/math-comp.git#master
        - run: opam pin --ignore-constraints-on elpi add coq-mathcomp-algebra https://github.com/math-comp/math-comp.git#master
        - run: opam pin --ignore-constraints-on elpi add coq-mathcomp-solvable https://github.com/math-comp/math-comp.git#master
        - run: opam pin --ignore-constraints-on elpi add coq-mathcomp-field https://github.com/math-comp/math-comp.git#master
